name: Deploy Blazor WebAssembly App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0'
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Install npm dependencies and sass
      run: |
        npm install
        npm install -g sass

    - name: Build the app
      run: dotnet build -c Release

    - name: Publish the app
      run: dotnet publish EPK.csproj -c Release --output release --nologo

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: release/wwwroot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
