name: Deploy Blazor WebAssembly App to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.3.0
      with:
        dotnet-version: '9.0'

    - name: Install .NET WebAssembly Tools
      run: dotnet workload install wasm-tools
    
    - name: Setup Node.js (for SASS)
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: |
        npm install
        npm install sass
    
    - name: Build SASS
      run: npm run build:sass

    - name: Publish the app
      run: dotnet publish EPK.sln -c:Release -o:publish -p:GHPages=true

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: publish/wwwroot
        force_orphan: true
