name: Deploy Blazor WebAssembly App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.3.0
      with:
        dotnet-version: '9.0'

    - name: Publish the app
      run: dotnet publish -c Release -o publish

    - name: Deploy to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: publish/wwwroot